Fix configure script when using CC=, CXX=.
git-svn-id: https://svn.mech.kuleuven.be/repos/orocos/trunk/rtt@6819 ce417995-dfc9-0310-95a0-acdaff106893

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -86,7 +86,9 @@ fi
 CMAKE_EXE=$(which cmake)
 
 echo "Invoking: '$CMAKE_CC $CMAKE_CXX $CMAKE_EXE .. $CMAKE_ARGS'"
-$CMAKE_CC $CMAKE_CXX $CMAKE_EXE .. $CMAKE_ARGS || { echo -e "\ncmake produced an error - removing cache."; rm CMakeCache.txt; exit 1; }
+export $CMAKE_CC 
+export $CMAKE_CXX 
+$CMAKE_EXE .. $CMAKE_ARGS || { echo -e "\ncmake produced an error - removing cache."; rm CMakeCache.txt; exit 1; }
 
 echo
 echo "OK: configure done. Now issue 'make'."
