* Moved doxygen to build dir * Improved ecos tools use in makefile * Improved pkg upgrading * Added release notes for 0.20.0
git-svn-id: https://svn.mech.kuleuven.be/repos/orocos/orocos-trunk@2510 ce417995-dfc9-0310-95a0-acdaff106893

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -8,7 +8,7 @@ EXTRA_DIST = \
 	packages/ecosadmin.tcl packages/ecosdbgen.py packages/ecospkggen.py \
 	packages/configure.ac packages/configure \
 	packages/aclocal.m4 packages/acinclude.m4 \
-	packages/Makefile.in packages/Doxyfile.in \
+	packages/Makefile.in Doxyfile.in \
 	doc/CODING_STYLE.txt \
 	packages/support/common/current/support.cdl.in \
 	packages/support/boost/current/boost.cdl.in \
@@ -45,13 +45,13 @@ inst-headers:
 	${MAKE} -C packages headers
 
 check-headers: clean_headers init_packages inst-headers
-	@cd packages/install/include ;\
+	cd packages/install/include ;\
 	tname=$$(tempfile -p check -s .cpp) ;\
-	for i in $$(find . -name *.h -o -name *.hpp); do \
+	for i in $$(find . -name "*.h" -o -name "*.hpp"); do \
 	echo  "Checking $$i..." ;\
 	echo -e "#include <$$i>\n" > $$tname ;\
-	${CC} -c $$tname -I. ;\
-	done ; rm $$tname
+	${CC} -pipe -W -Wall -S $$tname -I. ;\
+	done ; rm $$tname $$(basename $$tname cpp)s
 
 clean-local: clean_packages
 
@@ -88,15 +88,15 @@ new_packages:
 	@echo "Setting up packages..."
 	@cd packages &&\
 	export ECOS_REPOSITORY=$(ECOS_REP);\
-	ecosconfig new $(ECOS_TARGET) minimal 2>&1 > /dev/null ;\
+	$(ECOSCONFIG) new $(ECOS_TARGET) minimal 2>&1 > /dev/null ;\
 	if test -f ecos.ecc; then \
 	echo "Setting up support..." ; \
-	ecosconfig add support 2>&1 > /dev/null ; \
+	$(ECOSCONFIG) add support 2>&1 > /dev/null ; \
 	for i in $$(find $(ECOS_REP)/support -name "*.cdl" -a -not -name "support.cdl"); do \
-	ecosconfig add support_$$(basename $$i .cdl) 2>/dev/null ; done ;\
-	{ ecosconfig template dist-packages || ecosconfig template corelib-os; };\
+	$(ECOSCONFIG) add support_$$(basename $$i .cdl) 2>/dev/null ; done ;\
+	{ $(ECOSCONFIG) template dist-packages || $(ECOSCONFIG) template corelib-os; };\
 	echo -e "\n This is now your new configuration :\n" ;\
-	ecosconfig check ;\
+	$(ECOSCONFIG) check ;\
 	rm -f .configure-stamp .all-stamp ; else touch .configure-stamp .all-stamp ;\
 	fi
 	@touch .new-pkg-stamp
@@ -111,8 +111,8 @@ configure_packages: test_new_packages
 	@cd packages &&\
 	export ECOS_REPOSITORY=$(ECOS_REP) &&\
 	ln -sf ecos.ecc orocos.ecc &&\
-	configtool orocos.ecc &&\
-	ecosconfig export .upgrade.ecc
+	$(CONFIGTOOL) orocos.ecc &&\
+	$(ECOSCONFIG) export .upgrade.ecc
 
 
 test_all_packages: .all-stamp
@@ -129,8 +129,8 @@ dist_packages:
 	if test -f packages/ecos.ecc; then \
 	cd packages; \
 	export ECOS_REPOSITORY=$(ECOS_REP) ;\
-	ecosconfig template dist-packages;\
-	ecosconfig check ; fi
+	$(ECOSCONFIG) template dist-packages;\
+	$(ECOSCONFIG) check ; fi
 	$(MAKE) -C . packages
 
 # make all packages from current template
@@ -139,14 +139,14 @@ packages: init_packages
 	cd packages &&\
 	{ test -f ecos.ecc || exit 0; } &&\
 	{ $(MAKE) -C . || exit -1; } &&\
-	ECOS_REPOSITORY=$(ECOS_REP) ecosconfig export .upgrade.ecc &&\
+	ECOS_REPOSITORY=$(ECOS_REP) $(ECOSCONFIG) export .upgrade.ecc &&\
 	cd install/lib && ln -sf libtarget.a liborocos-$(ECOS_TARGET).a
 
 init_packages: test_new_packages
 	@cd packages &&\
 	{ test -f ecos.ecc || exit 0; } &&\
 	export ECOS_REPOSITORY=$(ECOS_REP) &&\
-	{ ecosconfig tree || { echo -e "\necosconfig tree failed.\n  Try 'make upgrade_packages' or contact the Orocos-dev mailinglist.\n"; exit -1; } }
+	{ $(ECOSCONFIG) tree || { echo -e "\n$(ECOSCONFIG) tree failed.\n  Try 'make upgrade_packages' or contact the Orocos-dev mailinglist.\n"; exit -1; } }
 
 precompile_headers:
 	$(MAKE) headers -C packages
@@ -163,12 +163,28 @@ control_services: test_new_packages
 	@if test -f packages/ecos.ecc; then \
 	cd packages; \
 	export ECOS_REPOSITORY=$(ECOS_REP) ;\
-	ecosconfig template controlservices;\
-	ecosconfig check ; fi
+	$(ECOSCONFIG) template control-services;\
+	$(ECOSCONFIG) check ; fi
 	$(MAKE) -C . packages
 
 #Build most of Orocos, except device drivers.
 robot_control: test_new_packages dist_packages
+
+doxygen_headers:
+	@if test -f packages/ecos.ecc; then \
+	cd packages; \
+	export ECOS_REPOSITORY=$(ECOS_REP) ;\
+	$(ECOSCONFIG) template doxygen;\
+	$(ECOSCONFIG) tree ;fi
+	$(MAKE) -C . inst-headers
+
+doxy-dist: test_new_packages 
+	@echo "Running Doxygen... (warnings in doxygen.warnings)"
+	@rm -rf doc/api
+	@mkdir -p doc/api	
+	@doxygen >/dev/null || (echo "doxygen failed !" ; exit 1)
+	@if [ -d doc ] ; then echo "Tarring API docs..." ;\
+	tar -cjf orocos-api.tar.bz2 doc/api; fi
 
 # This cleans out the object files but leaves
 # the headers and library
@@ -189,7 +205,7 @@ test_check_packages: .check-stamp
 check_packages:
 	cd packages ;\
 	export ECOS_REPOSITORY=$(ECOS_REP) ;\
-	ecosconfig -v check
+	$(ECOSCONFIG) -v check
 
 # This removes the whole ! packages build directory
 mrproper:
@@ -204,9 +220,13 @@ clean_install: clean-local
 
 # use this to *try* to fix your .ecc file in an upgrade
 upgrade_packages:
+	@if test -f packages/ecos.ecc; then \
 	export ECOS_REPOSITORY=$(ECOS_REP) ; cd packages ;\
-	$(MAKE) -C .. new_packages &&\
-	ecosconfig import .upgrade.ecc
+	$(ECOSCONFIG) new $(ECOS_TARGET) minimal ;\
+	$(ECOSCONFIG) import .upgrade.ecc ;\
+	$(ECOSCONFIG) resolve || echo -e "\nUpgrade failed. Start with a new configuration or manually remove the offending option from the packages/orocos.ecc file.\n" ;\
+	echo "" ; $(ECOSCONFIG) check ;\
+	fi
 
 ########################################################################
 # KUL specific :
@@ -215,25 +235,25 @@ new_drivers:
 	mkdir -p drv-$(ECOS_TARGET)
 	cd drv-$(ECOS_TARGET) ;\
 	export ECOS_REPOSITORY=$(ECOS_REP) ;\
-	ecosconfig -v new $(ECOS_TARGET) kuldrivers > new_drivers.log ; \
+	$(ECOSCONFIG) -v new $(ECOS_TARGET) kuldrivers > new_drivers.log ; \
 	for i in $$(find $(ECOS_REP)/support -name "*.cdl"); do \
-	ecosconfig add support_$$(basename $$i .cdl) > support.log; done
+	$(ECOSCONFIG) add support_$$(basename $$i .cdl) > support.log; done
 
 configure_drivers:
 	cd drv-$(ECOS_TARGET) ;\
 	export ECOS_REPOSITORY=$(ECOS_REP) ;\
-	configtool ecos.ecc
+	$(CONFIGTOOL) ecos.ecc
 
 all_drivers:
 	cd drv-$(ECOS_TARGET) ;\
 	export ECOS_REPOSITORY=$(ECOS_REP) ;\
-	ecosconfig -v tree
+	$(ECOSCONFIG) -v tree
 	$(MAKE) -C drv-$(ECOS_TARGET)
 
 check_drivers:
 	cd drv-$(ECOS_TARGET) ;\
 	export ECOS_REPOSITORY=$(ECOS_REP) ;\
-	ecosconfig -v check
+	$(ECOSCONFIG) -v check
 
 clean_drivers:
 	$(MAKE) -C drv-$(ECOS_TARGET) clean
